# Generated by Django 3.2.4 on 2023-09-10 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('price', models.FloatField()),
                ('flavour', models.CharField(max_length=150)),
                ('food_mate', models.CharField(max_length=150)),
                ('country', models.CharField(max_length=50)),
            ],
        ),
    ]
